kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: frontendreactapp
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontendreactapp
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: sameermosesmurala/frontendreactapp
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]