apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendkafka1
  labels:
    app: backendkafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendkafka1
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: 'true'
      labels:
        app: backendkafka1
    spec:
      containers:
        - name: backendkafka1
          image: sameermosesmurala/backendkafka1
          ports:
            - containerPort: 8082