apiVersion: v1
kind: Service
metadata:
  name: backendkafka1-service
spec:
  ports:
    - name: springtempbackend
      port: 8082
      targetPort: 8082
    - name: backendcollector
      port: 5555
      targetPort: 5555
  selector:
    app: backendkafka1
  type: LoadBalancer