apiVersion: v1
kind: Service
metadata:
  name: springtempbackend-service
spec:
  ports:
    - name: springtempbackend
      port: 8082
      nodePort: 30001
      targetPort: 8082
    - name: backendcollector
      port: 5555
      targetPort: 5555
  selector:
    app: springtempbackend
  type: NodePort