apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendcor
  labels:
    app: backendcor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendcor
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: 'true'
      labels:
        app: backendcor
    spec:
      containers:
        - name: backendcor
          image: deepctewari/backend-050823
          ports:
            - containerPort: 8082